theme: jekyll-theme-cayman
title: Objective Metrics to Evaluate Residual-Echo Suppression During Double-Talk
description: Amir Ivry, Prof. Israel Cohen, and Dr. Baruch Berdugo <br/>
Andrew and Erna Viterbi Faculty of Electrical and Computer Engineering, Technion - Israel Institute of Technology <br/>
This research was supported by the Pazy Research Foundation, the Israel Science Foundation (ISF), and the International Speech Communication Association (ISCA)
