theme: jekyll-theme-cayman
title: Objective Metrics to Evaluate Residual-Echo Suppression During Double-Talk
description: Amir Ivry, Prof. Israel Cohen, and Dr. Baruch Berdugo |
Andrew and Erna Viterbi Faculty of Electrical and Computer Engineering, Technion - Israel Institute of Technology |
Supported by Pazy Research Foundation, Israel Science Foundation (ISF), and International Speech Communication Association (ISCA)
